$Flow = @{
    "All" = @{
        "Save" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Save-PFAll -InputObject `$InputObject -path `$path -File `$file"
        "Restore" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Restore-PFAll -InputObject `$InputObject -path `$path -File `$file"
    }


    "alias" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFAlias -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-pfalias -InputObject `$InputObject -Alias `$Alias -Type `$Type -address `$Address -detail `$detail -Description `$Description"
        "edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; edit-pfalias -InputObject `$InputObject -Alias `$Alias -Type `$Type -address `$Address -detail `$detail -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Delete-pfalias -InputObject `$InputObject -Alias `$Alias"
        "AddEntry" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; AddEntry-pfalias -InputObject `$InputObject -Alias `$Alias -address `$Address -detail `$detail"
        "DeleteEntry" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; DeleteEntry-pfalias -InputObject `$InputObject -Alias `$Alias -detail `$detail"
    }

    "dhcpd" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFDHCPd -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-PFDHCPd -InputObject `$InputObject -Interface `$Interface -From `$From -To `$To -netmask `$netmask -Domain `$Domain -Gateway `$Gateway -DNSServer `$DNSServer -NTPServer `$NTPServer "
        "Set" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-PFDHCPd -InputObject `$InputObject -Interface `$Interface -From `$From -To `$To -netmask `$netmask -Domain `$Domain -Gateway `$Gateway -DNSServer `$DNSServer -NTPServer `$NTPServer "
        "Enable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; EnableOrDisable-PFDHCPd -InputObject `$InputObject -Interface `$Interface -EnableOrDisable `$True"
        "Disable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; EnableOrDisable-PFDHCPd -InputObject `$InputObject -Interface `$Interface -EnableOrDisable `$False"

    } 
    "dhcpStaticMap" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFDHCPstaticmap -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-PFDHCPstaticmap -InputObject `$InputObject -Interface `$Interface -Hostname `$Hostname -Domain `$Domain -ClientID `$ClientID -MACaddr `$MACaddr -Address `$Address -Description `$Description -Gateway `$Gateway -DNSserver `$DNSserver -NTPServer `$NTPServer"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-PFDHCPstaticmap -InputObject `$InputObject -Interface `$Interface -Hostname `$Hostname -Domain `$Domain -ClientID `$ClientID -MACaddr `$MACaddr -Address `$Address -Description `$Description -Gateway `$Gateway -DNSserver `$DNSserver -NTPServer `$NTPServer"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Delete-PFDHCPstaticmap -InputObject `$InputObject -Interface `$Interface -MACaddr `$MACaddr"
    }  
    "dnsResolver" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFUnbound -InputObject `$InputObject"
    }    
    "dnsResolverHost" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFUnboundHost -InputObject `$InputObject"
    }   
    "Firewall" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFFirewall -InputObject `$InputObject"
    } 

    "gateway" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFGateway -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Add-PFGateway -InputObject `$InputObject -name `$name -Interface `$Interface -Gateway `$Gateway -Weight `$Weight -Monitor `$Monitor -Protocol `$Protocol -Description `$Description"
    }

    "interface" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFInterface -InputObject `$InputObject"
    }

    "portfwd" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFNatRule -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Add-PFNatRule -InputObject `$InputObject -Interface `$Interface -Protocol `$Protocol -SourceAddress `$SourceAddress -SourcePort `$SourcePort -DestAddress `$DestAddress -DestPort `$DestPort -NatIp `$NatIp -NatPort `$NatPort -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Delete-PFNatRule -InputObject `$InputObject -Interface `$Interface -Protocol `$Protocol -SourceAddress `$SourceAddress -SourcePort `$SourcePort -DestAddress `$DestAddress -DestPort `$DestPort -NatIp `$NatIp -NatPort `$NatPort -Description `$Description"
    }    

    "StaticRoute" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFStaticRoute -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-PFStaticRoute -InputObject `$InputObject -Network `$Network -Gateway `$Gateway -Description `$Description"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Add-PFStaticRoute -InputObject `$InputObject -Network `$Network -Gateway `$Gateway -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name) ; Delete-PFStaticRoute -InputObject `$InputObject -Network `$Network"
    }
    "Vlan" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name); Write-PFVlan -InputObject `$InputObject"
    }
}