$Flow = @{
    "All" = @{
        "Save" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Save-PFAll -InputObject `$InputObject -path `$path -File `$file"
        "Restore" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Restore-PFAll -InputObject `$InputObject -path `$path -File `$file"
    }


    "alias" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFAlias -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Add-pfalias -InputObject `$InputObject -Name `$Alias -Type `$Type -address `$Address -detail `$detail -Description `$Description"
        "edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; edit-pfalias -InputObject `$InputObject -Alias `$Alias -Type `$Type -address `$Address -detail `$detail -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Delete-pfalias -InputObject `$InputObject -Alias `$Alias"
        "AddEntry" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; AddEntry-pfalias -InputObject `$InputObject -Alias `$Alias -address `$Address -detail `$detail"
        "DeleteEntry" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; DeleteEntry-pfalias -InputObject `$InputObject -Alias `$Alias -address `$Address -detail `$detail"
    }

    "cert" = @{
        "Print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFCert -InputObject `$InputObject"
    }

    "dhcpd" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFDHCPd -InputObject `$InputObject"
        "edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Edit-PFDHCPd -InputObject `$InputObject -Interface `$Interface -RangeFrom `$From -RangeTo `$To -netmask `$netmask -Domain `$Domain -Gateway `$Gateway -DNSServer `$DNSServer -NTPServer `$NTPServer "
        "Enable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Edit-PFDHCPd -InputObject `$InputObject -Interface `$Interface -enable `$True"
        "Disable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Edit-PFDHCPd -InputObject `$InputObject -Interface `$Interface -enable `$False"

    } 
    "dhcpStaticMap" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFDHCPstaticmap -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Add-PFDHCPstaticmap -InputObject `$InputObject -Intface `$Interface -Hostname `$Hostname -Domain `$Domain -ClientID `$ClientID -MACaddr `$MACaddr -IPaddr `$Address -Description `$Description -Gateway `$Gateway -DNSserver `$DNSserver -NTPServer `$NTPServer"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; edit-PFDHCPstaticmap -InputObject `$InputObject -Interface `$Interface -Hostname `$Hostname -Domain `$Domain -ClientID `$ClientID -MACaddr `$MACaddr -Address `$Address -Description `$Description -Gateway `$Gateway -DNSserver `$DNSserver -NTPServer `$NTPServer"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Delete-PFDHCPstaticmap -InputObject `$InputObject -Interface `$Interface -MACaddr `$MACaddr"
    }  
    "dnsForwarder" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFDnsMasq -InputObject `$InputObject"
    }
    "dnsResolver" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFUnbound -InputObject `$InputObject"
        "edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFUnbound -InputObject `$InputObject -ActiveInt `$ActiveInt -OutgoingInterface `$OutgoingInterface -dnssec `$dnssec -port `$port -sslport `$sslport -CustomOptions `$CustomOptions -sslcertref `$sslcertref"
        "Disable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFUnbound -InputObject `$InputObject -enable `$False"
        "Enable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFUnbound -InputObject `$InputObject -enable `$True"
    }    
    "dnsResolverHost" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFUnboundHost -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFUnboundHost -InputObject `$InputObject -Hostname `$Hostname -Domain `$Domain -Address `$Address -Description `$Description"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFUnboundHost -InputObject `$InputObject -Hostname `$Hostname -Domain `$Domain -Address `$Address -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFUnboundHost -InputObject `$InputObject -Hostname `$Hostname -Domain `$Domain"
        "AliasAdd" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFUnboundHostAlias -InputObject `$InputObject -Hostname `$Hostname -Domain `$Domain -HostNameAlias `$HostNameAlias -DomainAlias `$DomainAlias -DescriptionAlias `$DescriptionAlias "
        "AliasDelete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFUnboundHostAlias -InputObject `$InputObject -Hostname `$Hostname -Domain `$Domain -HostNameAlias `$HostNameAlias -DomainAlias `$DomainAlias -DescriptionAlias `$DescriptionAlias "
    }   
    "dnsResolverDomain" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFUnboundDomain -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFUnboundDomain -InputObject `$InputObject -Domain `$Domain -Address `$Address -TLSQueries `$TLSQueries -TlsHostname `$TlsHostname -Description `$Description"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFUnboundDomain -InputObject `$InputObject -Domain `$Domain -Address `$Address -TLSQueries `$TLSQueries -TlsHostname `$TlsHostname -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFUnboundDomain -InputObject `$InputObject -Domain `$Domain"
    }
    "Firewall" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFFirewall -InputObject `$InputObject"
        "add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFFirewall -InputObject `$InputObject -IsFloating `$IsFloating -IsQuick `$IsQuick -IsLogged `$IsLogged -Type `$Type -IPProtocol `$IPProtocol -interface `$interface -Protocol `$Protocol -SourceAddress `$SourceAddress -SourcePort `$SourcePort -DestinationAddress `$DestAddress -DestinationPort `$DestPort -Description `$Description -NewLineNumber `$NewLineNumber"
        "edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFFirewall -InputObject `$InputObject -tracker `$tracker -IsFloating `$IsFloating -IsQuick `$IsQuick -IsLogged `$IsLogged -Type `$Type -IPProtocol `$IPProtocol -interface `$interface -Protocol `$Protocol -SourceAddress `$SourceAddress -SourcePort `$SourcePort -DestinationAddress `$DestAddress -DestinationPort `$DestPort -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFFirewall -InputObject `$InputObject -tracker `$tracker"
        "Up" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); UpDown-PFFirewall -InputObject `$InputObject -tracker `$tracker -up"
        "Down" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); UpDown-PFFirewall -InputObject `$InputObject -tracker `$tracker"
        "Move" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Move-PFFirewall -InputObject `$InputObject -OldLineNumber `$OldLineNumber -NewLineNumber `$NewLineNumber"
    } 
    "gateway" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFGateway -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFGateway -InputObject `$InputObject -name `$name -Interface `$Interface -Gateway `$Gateway -Weight `$Weight -Monitor `$Monitor -Protocol `$Protocol -Description `$Description"
        "edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFGateway -InputObject `$InputObject -name `$name -Interface `$Interface -Gateway `$Gateway -Weight `$Weight -Monitor `$Monitor -Protocol `$Protocol -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFGateway -InputObject `$InputObject -name `$name"
    }
    "interface" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFInterface -InputObject `$InputObject"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFInterface -InputObject `$InputObject -Name `$Name -Description `$Description -Interface `$Interface -IPv4Address `$IPv4Address -IPv4Subnet `$IPv4Subnet -IPv4Gateway `$IPv4Gateway -IPv6Address `$IPv6Address -IPv6Subnet `$IPv6Subnet -IPv6Gateway `$IPv6Gateway -blockpriv `$blockpriv -BlockBogons `$BlockBogons"
        "Enable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFInterface -InputObject `$InputObject -Description `$Description -enable `$True"
        "Disable" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Edit-PFInterface -InputObject `$InputObject -Description `$Description -enable `$False"
    }

    "portfwd" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFNatRule -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFNatRule -InputObject `$InputObject -Interface `$Interface -Protocol `$Protocol -SourceAddress `$SourceAddress -SourcePort `$SourcePort -DestAddress `$DestAddress -DestPort `$DestPort -NatIp `$NatIp -NatPort `$NatPort -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFNatRule -InputObject `$InputObject -Interface `$Interface -Protocol `$Protocol -SourceAddress `$SourceAddress -SourcePort `$SourcePort -DestAddress `$DestAddress -DestPort `$DestPort -NatIp `$NatIp -NatPort `$NatPort -Description `$Description"
    }    

    "StaticRoute" = @{
        "print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFStaticRoute -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Add-PFStaticRoute -InputObject `$InputObject -Network `$Network -Gateway `$Gateway -Description `$Description"
        "Edit" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Edit-PFStaticRoute -InputObject `$InputObject -Network `$Network -Gateway `$Gateway -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority) ; Delete-PFStaticRoute -InputObject `$InputObject -Network `$Network"
    }
    "Vlan" = @{
        "Print" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Write-PFVlan -InputObject `$InputObject"
        "Add" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Add-PFVlan -InputObject `$InputObject -Interface `$Interface -Tag `$Tag -Priority `$Priority -Description `$Description"
        "Delete" = "param(`$InputObject,`$path,`$file,`$Network,`$Gateway,`$Description,`$Interface,`$From,`$To,`$netmask,`$Domain,`$DNSServer,`$NTPServer,`$Alias,`$Type,`$Address,`$Detail,`$HostName,`$ClientID,`$MacAddr,`$Protocol,`$SourceAddress,`$DestAddress,`$DestPort,`$NatIp,`$NatPort,`$Weight,`$Monitor,`$Name,`$IpProtocol,`$IsLogged,`$IsQuick,`$IsFloating,`$tracker,`$OldLineNumber,`$NewLineNumber,`$IPv4Address,`$IPv4Subnet,`$IPv4Gateway,`$IPv6Address,`$IPv6Subnet,`$IPv6Gateway,`$blockpriv,`$BlockBogons,`$ActiveInt,`$OutgoingInterface,`$dnssec,`$sslport,`$CustomOptions,`$sslcertref,`$port,`$HostNameAlias,`$DomainAlias,`$DescriptionAlias,`$TLSQueries,`$TlsHostname,`$Tag,`$Priority); Delete-PFVlan -InputObject `$InputObject -Interface `$Interface -Tag `$Tag"
    }
}